application: techme2-eu
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /admin/.*
  script: main.py
  login: admin

- url: /css
  static_dir: media/css

- url: /img
  static_dir: media/img
  
- url: /scripts
  static_dir: media/scripts

- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico

- url: /robots\.txt
  static_files: media/robots.txt
  upload: media/robots.txt

- url: /.*
  script: main.py